PROFILE_TYPE_VENDOR = "Vendor"
PROFILE_TYPE_CUSTOMER = 'Customer'
PROFILE_TYPE_ADMIN = 'Admin'

PROFILE_TYPE = (
    (PROFILE_TYPE_VENDOR, "Vendor"),
    (PROFILE_TYPE_CUSTOMER, "Customer"),
    (PROFILE_TYPE_ADMIN, "Admin")
)

PRODUCT_CATEGORY_CUTLERY = "cutlery"
PRODUCT_CATEGORY_MEDICINES = 'medicines'
PRODUCT_CATEGORY_FURNITURES = 'furnitures'
PRODUCT_CATEGORY_ELECTRONICS = 'electronics'

PRODUCT_CATEGORIES = (
    (PRODUCT_CATEGORY_ELECTRONICS, 'electronics'),
    (PRODUCT_CATEGORY_FURNITURES, 'furnitures'),
    (PRODUCT_CATEGORY_MEDICINES, 'medicines'),
    (PRODUCT_CATEGORY_CUTLERY, "cutlery")
)

PRODUCT_TYPE_PRODUCT = "product"
PRODUCT_TYPE_SERVICE = 'service'

PRODUCT_TYPES = (
    (PRODUCT_TYPE_PRODUCT, "Product"),
    (PRODUCT_TYPE_SERVICE, "Service")
)


ORDER_STATUS_COMPLETED = "completed"
ORDER_STATUS_UPCOMING = 'upcoming'
ORDER_STATUS_CANCELLED = 'cancelled'

ORDER_STATUS = (
    (ORDER_STATUS_COMPLETED, "Completed"),
    (ORDER_STATUS_UPCOMING, "Upcoming"),
    (ORDER_STATUS_CANCELLED, "Cancelled")
)

PAYMENT_STATUS_SUCCESSFULL = "successful"
PAYMENT_STATUS_PENDING = 'pending'

PAYMENT_STATUS = (
    (PAYMENT_STATUS_SUCCESSFULL, "Successful"),
    (PAYMENT_STATUS_PENDING, "Pending")
)