# Generated by Django 3.0.5 on 2021-04-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(blank=True, max_length=100)),
                ('locality', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('completed', 'Completed'), ('upcoming', 'Upcoming'), ('cancelled', 'Cancelled')], default='upcoming', max_length=1024)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_setting', models.BooleanField(default=True)),
                ('address_setting', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorId', models.IntegerField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('sales', models.IntegerField(default=0)),
                ('timings', models.TextField()),
                ('product_availability', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=5)),
                ('product_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=1024)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_type', models.CharField(choices=[('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Admin', 'Admin')], default='Customer', max_length=1024)),
                ('vendor_description', models.TextField(null=True)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(max_length=10)),
                ('image', models.URLField(max_length=1000)),
                ('last_app_activity', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_admin_verified', models.BooleanField(default=False)),
                ('privacy_setting', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_api.PrivacySettings')),
            ],
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_api.Profiles'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('pending', 'Pending')], default='pending', max_length=1024)),
                ('amount', models.IntegerField()),
                ('details', models.TextField()),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders_payments_rn', to='admin_api.Orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer_rn', to='admin_api.Profiles'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product_rn', to='admin_api.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_vendor_rn', to='admin_api.Profiles'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_contacts_rn', to='admin_api.Profiles')),
            ],
        ),
    ]
