# Generated by Django 3.0.5 on 2021-04-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='vendorId',
        ),
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor_rn', to='admin_api.Profiles'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_contacts', to='admin_api.Profiles'),
        ),
    ]
