# Generated by Django 3.0.5 on 2021-04-14 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_api.Profiles'),
            preserve_default=False,
        ),
    ]
