# Generated by Django 3.0.5 on 2021-04-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_auto_20210424_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('electronics', 'electronics'), ('furnitures', 'furnitures'), ('medicines', 'medicines'), ('cutlery', 'cutlery')], default='electronics', max_length=1024),
            preserve_default=False,
        ),
    ]
