# Generated by Django 3.0.5 on 2021-05-02 18:25

import django.core.validators
from django.db import migrations, models
import utility.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_auto_20210429_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('completed', 'completed'), ('upcoming', 'upcoming'), ('cancelled', 'cancelled')], default='upcoming', max_length=1024),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('successful', 'successful'), ('pending', 'pending')], default='pending', max_length=1024),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('product', 'product'), ('service', 'service')], default='product', max_length=1024),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10, validators=[utility.utilities.ModelChoicesUtilities.profile_gender_validator]),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile_type',
            field=models.CharField(choices=[('vendor', 'vendor'), ('customer', 'customer'), ('admin', 'admin')], default='customer', max_length=1024, validators=[utility.utilities.ModelChoicesUtilities.profile_type_validator]),
        ),
    ]
