# Generated by Django 3.0.5 on 2021-05-02 20:55

import admin_api.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_auto_20210502_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(unique=True, validators=[admin_api.profiles.models.validate_profile_contact_pattern]),
        ),
    ]
